dist: trusty
language: python
python: 3.6
addons:
  chrome: stable
install:
- pip install requests selenium
- wget https://raw.githubusercontent.com/Alivon/Panda-Learning/master/pandalearn.py -O pandalearn.py
script: echo -e "$user\n$password" | python pandalearn.py
